### ISSUE TITLE
Feedback about game from different people

### ISSUE THREAD

**Issue by scabbiaza** [Paqmind/memory-game#6]
1.  New game: you need to click on ‘new game’ to start, http://screencast.com/t/D3IUHQYmG and this hard to realize (most people will just start hitting the squares until realizing they need to do something else). I think ‘Play’ is a more accurate word than ‘New Game’ and also position/herarchy, it should be the first thing you see and the element that gets your attention the most.
2. When you loose, you need to exit. And then hitting ‘new game’ again (too many steps). a ‘play again’ icon will be wonderful to keep the user hooked with out disrupting.

---

I would put option "Try again" after you loose the game, Instead of Exit
and by default it should load the game when we open page. It took me some time to realise I have to click on New game
And "Exit" should lead you outside the game

---

maybe some colors changes? cuz for old ppl with glasses (like me) black and white are not easy to focus on :sweat_smile:

---

I would suggest that you start a new game automatically when the user clicks on the back backs of the cards 
I didn't notice the New Game button the first time
or you can make an overlay on the cards with the words `New Game` and make it clickable

---

letters not so visual for me) pictures will be easier for me and digits even harder) You also can use different colors/styles for letter

**Comment by ivan-kleshnin** [comment]
Game should not start immediately but there is definitely a ground for complaints.
- [x] Rename "New Game" to "Start Game"
- [x] Add "Try again" button (keeping "Exit").
- [x] Render empty cards (before game start) with dark gray (not black)

**Comment by ivan-kleshnin** [comment]
Done
